### ISSUE TITLE
strptime on only an3 - should have been fixed in last update 

### ISSUE THREAD

**Issue by lthurlow** [lthurlow/scaling-computing-machine#9]
```
[rip.py:95 - Thread-2        check_timeout]      DEBUG CHECK_TIMEOUT (eth2) 
[rip.py:95 - Thread-3        check_timeout]      DEBUG CHECK_TIMEOUT (eth3) 
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "../anhost/rip.py", line 169, in send_handler
    send_update(sock, n_fi,port,dev,mgmt)
  File "../anhost/rip.py", line 146, in send_update
    rip_update = check_timeout(n_fi,rip_update,mgmt,dev)
  File "../anhost/rip.py", line 107, in check_timeout
    if (current_time-r.get_ttl() > datetime.timedelta(minutes=2)):
  File "../anhost/anhost.py", line 62, in get_ttl
    return datetime.datetime.strptime(self.update,"%Y%j%H%M%S%f")
AttributeError: _strptime
```

**Comment by lthurlow** [comment]
can't reproduce.
